services:
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app:cached
      - ./frontend:/usr/src/frontend:ro
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHROMIUM_PATH=/usr/bin/chromium
    ports:
      - '3000:3000'

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
      - VITE_API_URL=http://localhost:3000 
    ports:
      - '5173:5173'
    depends_on:
      - backend-dev
